(function(){'use strict';var n;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var p=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var q=ba(this);function r(a,b){if(b)a:{var c=q;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&p(c,a,{configurable:!0,writable:!0,value:b})}}
r("Symbol",function(a){function b(k){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(k||"")+"_"+e++,k)}function c(k,f){this.g=k;p(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=q[b[c]];typeof d==="function"&&typeof d.prototype[a]!="function"&&p(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(aa(this))}})}return a});function ca(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function da(a){return a.raw=a}function t(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}var ea=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},fa;
if(typeof Object.setPrototypeOf=="function")fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ma=fa;function na(){this.l=!1;this.h=null;this.i=void 0;this.g=1;this.A=0;this.j=null}function oa(a){if(a.l)throw new TypeError("Generator is already running");a.l=!0}na.prototype.u=function(a){this.i=a};
function pa(a,b){a.j={Z:b,aa:!0};a.g=a.A}na.prototype.return=function(a){this.j={return:a};this.g=this.A};function u(a,b,c){a.g=c;return{value:b}}function qa(a){this.g=new na;this.h=a}function ra(a,b){oa(a.g);var c=a.g.h;if(c)return sa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return v(a)}
function sa(a,b,c,d){try{var e=b.call(a.g.h,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.g.l=!1,e;var k=e.value}catch(f){return a.g.h=null,pa(a.g,f),v(a)}a.g.h=null;d.call(a.g,k);return v(a)}function v(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.l=!1,{value:b.value,done:!1}}catch(c){a.g.i=void 0,pa(a.g,c)}a.g.l=!1;if(a.g.j){b=a.g.j;a.g.j=null;if(b.aa)throw b.Z;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ta(a){this.next=function(b){oa(a.g);a.g.h?b=sa(a,a.g.h.next,b,a.g.u):(a.g.u(b),b=v(a));return b};this.throw=function(b){oa(a.g);a.g.h?b=sa(a,a.g.h["throw"],b,a.g.u):(pa(a.g,b),b=v(a));return b};this.return=function(b){return ra(a,b)};this[Symbol.iterator]=function(){return this}}function ua(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function k(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(k,e)}k(a.next())})}
function w(a){return ua(new ta(new qa(a)))}function va(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
r("Promise",function(a){function b(f){this.h=0;this.i=void 0;this.g=[];this.A=!1;var g=this.j();try{f(g.resolve,g.reject)}catch(h){g.reject(h)}}function c(){this.g=null}function d(f){return f instanceof b?f:new b(function(g){g(f)})}if(a)return a;c.prototype.h=function(f){if(this.g==null){this.g=[];var g=this;this.i(function(){g.l()})}this.g.push(f)};var e=q.setTimeout;c.prototype.i=function(f){e(f,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var f=this.g;this.g=[];for(var g=0;g<f.length;++g){var h=
f[g];f[g]=null;try{h()}catch(l){this.j(l)}}}this.g=null};c.prototype.j=function(f){this.i(function(){throw f;})};b.prototype.j=function(){function f(l){return function(m){h||(h=!0,l.call(g,m))}}var g=this,h=!1;return{resolve:f(this.V),reject:f(this.l)}};b.prototype.V=function(f){if(f===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.X(f);else{a:switch(typeof f){case "object":var g=f!=null;break a;case "function":g=!0;break a;default:g=!1}g?this.U(f):this.u(f)}};
b.prototype.U=function(f){var g=void 0;try{g=f.then}catch(h){this.l(h);return}typeof g=="function"?this.Y(g,f):this.u(f)};b.prototype.l=function(f){this.T(2,f)};b.prototype.u=function(f){this.T(1,f)};b.prototype.T=function(f,g){if(this.h!=0)throw Error("Cannot settle("+f+", "+g+"): Promise already settled in state"+this.h);this.h=f;this.i=g;this.h===2&&this.W();this.ba()};b.prototype.W=function(){var f=this;e(function(){if(f.ca()){var g=q.console;typeof g!=="undefined"&&g.error(f.i)}},1)};b.prototype.ca=
function(){if(this.A)return!1;var f=q.CustomEvent,g=q.Event,h=q.dispatchEvent;if(typeof h==="undefined")return!0;typeof f==="function"?f=new f("unhandledrejection",{cancelable:!0}):typeof g==="function"?f=new g("unhandledrejection",{cancelable:!0}):(f=q.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.i;return h(f)};b.prototype.ba=function(){if(this.g!=null){for(var f=0;f<this.g.length;++f)k.h(this.g[f]);this.g=null}};var k=new c;b.prototype.X=
function(f){var g=this.j();f.B(g.resolve,g.reject)};b.prototype.Y=function(f,g){var h=this.j();try{f.call(g,h.resolve,h.reject)}catch(l){h.reject(l)}};b.prototype.then=function(f,g){function h(B,F){return typeof B=="function"?function(ka){try{l(B(ka))}catch(la){m(la)}}:F}var l,m,z=new b(function(B,F){l=B;m=F});this.B(h(f,l),h(g,m));return z};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.B=function(f,g){function h(){switch(l.h){case 1:f(l.i);break;case 2:g(l.i);break;default:throw Error("Unexpected state: "+
l.h);}}var l=this;this.g==null?k.h(h):this.g.push(h);this.A=!0};b.resolve=d;b.reject=function(f){return new b(function(g,h){h(f)})};b.race=function(f){return new b(function(g,h){for(var l=t(f),m=l.next();!m.done;m=l.next())d(m.value).B(g,h)})};b.all=function(f){var g=t(f),h=g.next();return h.done?d([]):new b(function(l,m){function z(ka){return function(la){B[ka]=la;F--;F==0&&l(B)}}var B=[],F=0;do B.push(void 0),F++,d(h.value).B(z(B.length-1),m),h=g.next();while(!h.done)})};return b});
function x(a,b){return Object.prototype.hasOwnProperty.call(a,b)}r("Symbol.dispose",function(a){return a?a:Symbol("Symbol.dispose")});r("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,k=0;k<e;k++){var f=d[k];if(b.call(c,f,k,d)){b=f;break a}}b=void 0}return b}});
r("WeakMap",function(a){function b(h){this.g=(g+=Math.random()+1).toString();if(h){h=t(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(h){var l=typeof h;return l==="object"&&h!==null||l==="function"}function e(h){if(!x(h,f)){var l=new c;p(h,f,{value:l})}}function k(h){var l=Object[h];l&&(Object[h]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var h=Object.seal({}),l=Object.seal({}),
m=new a([[h,2],[l,3]]);if(m.get(h)!=2||m.get(l)!=3)return!1;m.delete(h);m.set(l,4);return!m.has(h)&&m.get(l)==4}catch(z){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();k("freeze");k("preventExtensions");k("seal");var g=0;b.prototype.set=function(h,l){if(!d(h))throw Error("Invalid WeakMap key");e(h);if(!x(h,f))throw Error("WeakMap key fail: "+h);h[f][this.g]=l;return this};b.prototype.get=function(h){return d(h)&&x(h,f)?h[f][this.g]:void 0};b.prototype.has=function(h){return d(h)&&x(h,
f)&&x(h[f],this.g)};b.prototype.delete=function(h){return d(h)&&x(h,f)&&x(h[f],this.g)?delete h[f][this.g]:!1};return b});
r("Map",function(a){function b(){var g={};return g.s=g.next=g.head=g}function c(g,h){var l=g[1];return ca(function(){if(l){for(;l.head!=g[1];)l=l.s;for(;l.next!=l.head;)return l=l.next,{done:!1,value:h(l)};l=null}return{done:!0,value:void 0}})}function d(g,h){var l=h&&typeof h;l=="object"||l=="function"?k.has(h)?l=k.get(h):(l=""+ ++f,k.set(h,l)):l="p_"+h;var m=g[0][l];if(m&&x(g[0],l))for(g=0;g<m.length;g++){var z=m[g];if(h!==h&&z.key!==z.key||h===z.key)return{id:l,list:m,index:g,o:z}}return{id:l,
list:m,index:-1,o:void 0}}function e(g){this[0]={};this[1]=b();this.size=0;if(g){g=t(g);for(var h;!(h=g.next()).done;)h=h.value,this.set(h[0],h[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var g=Object.seal({x:4}),h=new a(t([[g,"s"]]));if(h.get(g)!="s"||h.size!=1||h.get({x:4})||h.set({x:4},"t")!=h||h.size!=2)return!1;var l=h.entries(),m=l.next();if(m.done||m.value[0]!=g||m.value[1]!="s")return!1;m=l.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!l.next().done?!1:!0}catch(z){return!1}}())return a;var k=new WeakMap;e.prototype.set=function(g,h){g=g===0?0:g;var l=d(this,g);l.list||(l.list=this[0][l.id]=[]);l.o?l.o.value=h:(l.o={next:this[1],s:this[1].s,head:this[1],key:g,value:h},l.list.push(l.o),this[1].s.next=l.o,this[1].s=l.o,this.size++);return this};e.prototype.delete=function(g){g=d(this,g);return g.o&&g.list?(g.list.splice(g.index,1),g.list.length||delete this[0][g.id],g.o.s.next=g.o.next,g.o.next.s=g.o.s,g.o.head=
null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].s=b();this.size=0};e.prototype.has=function(g){return!!d(this,g).o};e.prototype.get=function(g){return(g=d(this,g).o)&&g.value};e.prototype.entries=function(){return c(this,function(g){return[g.key,g.value]})};e.prototype.keys=function(){return c(this,function(g){return g.key})};e.prototype.values=function(){return c(this,function(g){return g.value})};e.prototype.forEach=function(g,h){for(var l=this.entries(),m;!(m=l.next()).done;)m=
m.value,g.call(h,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var f=0;return e});r("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)x(b,d)&&c.push(b[d]);return c}});r("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});
r("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var k=d[c];if(k===b||Object.is(k,b))return!0}return!1}});
r("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return this.indexOf(b,c||0)!==-1}});r("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});
r("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});function wa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var k=c++;return{value:b(k,a[k]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}r("Array.prototype.keys",function(a){return a?a:function(){return wa(this,function(b){return b})}});
r("Array.prototype.values",function(a){return a?a:function(){return wa(this,function(b,c){return c})}});
r("Set",function(a){function b(c){this.g=new Map;if(c){c=t(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.g.size}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var c=Object.seal({x:4}),d=new a(t([c]));if(!d.has(c)||d.size!=1||d.add(c)!=d||d.size!=1||d.add({x:4})!=d||d.size!=2)return!1;var e=d.entries(),k=e.next();if(k.done||k.value[0]!=c||k.value[1]!=c)return!1;k=e.next();return k.done||k.value[0]==c||k.value[0].x!=4||
k.value[1]!=k.value[0]?!1:e.next().done}catch(f){return!1}}())return a;b.prototype.add=function(c){c=c===0?0:c;this.g.set(c,c);this.size=this.g.size;return this};b.prototype.delete=function(c){c=this.g.delete(c);this.size=this.g.size;return c};b.prototype.clear=function(){this.g.clear();this.size=0};b.prototype.has=function(c){return this.g.has(c)};b.prototype.entries=function(){return this.g.entries()};b.prototype.values=function(){return this.g.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=
b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.g.forEach(function(k){return c.call(d,k,k,e)})};return b});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var y=this||self;function A(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}function C(a,b){a=a.split(".");var c=y;a[0]in c||typeof c.execScript=="undefined"||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||b===void 0?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}
function xa(a,b){function c(){}c.prototype=b.prototype;a.C=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.da=function(d,e,k){for(var f=Array(arguments.length-2),g=2;g<arguments.length;g++)f[g-2]=arguments[g];return b.prototype[e].apply(d,f)}};function D(a,b){a=Error.call(this,a);this.message=a.message;"stack"in a&&(this.stack=a.stack);b=b===void 0?2:b;this.code=b>1E4?Math.floor(b/1E4):b}var E=Error;D.prototype=ea(E.prototype);D.prototype.constructor=D;if(ma)ma(D,E);else for(var G in E)if(G!="prototype")if(Object.defineProperties){var ya=Object.getOwnPropertyDescriptor(E,G);ya&&Object.defineProperty(D,G,ya)}else D[G]=E[G];D.C=E.prototype;C("microapps.ErrorCode.CANCELLED",1);C("microapps.ErrorCode.UNKNOWN",2);C("microapps.ErrorCode.INVALID_ARGUMENT",3);C("microapps.ErrorCode.DEADLINE_EXCEEDED",4);C("microapps.ErrorCode.NOT_FOUND",5);C("microapps.ErrorCode.ALREADY_EXISTS",6);C("microapps.ErrorCode.PERMISSION_DENIED",7);C("microapps.ErrorCode.RESOURCE_EXHAUSTED",8);C("microapps.ErrorCode.FAILED_PRECONDITION",9);C("microapps.ErrorCode.ABORTED",10);C("microapps.ErrorCode.OUT_OF_RANGE",11);C("microapps.ErrorCode.UNIMPLEMENTED",12);
C("microapps.ErrorCode.INTERNAL",13);C("microapps.ErrorCode.UNAVAILABLE",14);C("microapps.ErrorCode.DATA_LOSS",15);C("microapps.ErrorCode.UNAUTHENTICATED",16);var H=null;function za(){}n=za.prototype;n.D=function(){H().D()};n.K=function(a){return H().K(a)};n.P=function(a){return H().P(a)};n.R=function(a){return H().R(a)};n.G=function(a){return H().G(a)};n.J=function(a){return H().J(a)};n.L=function(a){return H().L(a)};n.N=function(a){return H().N(a)};n.M=function(a){return H().M(a)};n.O=function(a){return H().O(a)};n.v=function(a){return H().v(a)};n.I=function(a){return H().I(a)};function Aa(a,b){a=String(a).toLowerCase();b=String(b).toLowerCase();return a<b?-1:a==b?0:1};var I,J;a:{for(var Ba=["CLOSURE_FLAGS"],K=y,Ca=0;Ca<Ba.length;Ca++)if(K=K[Ba[Ca]],K==null){J=null;break a}J=K}var Da=J&&J[610401301];I=Da!=null?Da:!1;function Ea(){var a=y.navigator;return a&&(a=a.userAgent)?a:""}var L,Fa=y.navigator;L=Fa?Fa.userAgentData||null:null;function Ga(a){return I?L?L.brands.some(function(b){return(b=b.brand)&&b.indexOf(a)!=-1}):!1:!1}function M(a){return Ea().indexOf(a)!=-1};function N(){return I?!!L&&L.brands.length>0:!1}function Ha(){return N()?Ga("Chromium"):(M("Chrome")||M("CriOS"))&&!(N()?0:M("Edge"))||M("Silk")};var Ia=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ja=Array.prototype.every?function(a,b){return Array.prototype.every.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0};
function O(a){return Array.prototype.concat.apply([],arguments)};var Ka=I&&L&&L.platform?L.platform==="Android":M("Android"),La=M("iPhone")&&!M("iPod")&&!M("iPad")||M("iPad")||M("iPod");!M("Android")||Ha();Ha();M("Safari")&&(Ha()||(N()?0:M("Coast"))||(N()?0:M("Opera"))||(N()?0:M("Edge"))||(N()?Ga("Microsoft Edge"):M("Edg/"))||N()&&Ga("Opera"));function Ma(a){a.ea=!0;return a};var Na=/^(http:\/\/localhost\.corp|https:\/\/microapps(-(autopush|preprod|prod-tt|daily-[0-6]|autopush-qual|preprod-qual|staging-qual-sandbox|staging-qual-partner|daily-[0-6]-qual)\.sandbox)?)\.google\.com(:[0-9]+)?$/;/*

 SPDX-License-Identifier: Apache-2.0
*/
function P(a){this.g=a}P.prototype.toString=function(){return this.g};function Oa(a){for(var b=va.apply(1,arguments),c=[a[0]],d=0;d<b.length;d++)c.push(String(b[d])),c.push(a[d+1]);return new P(c.join(""))}var Pa=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;function Qa(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Ra(a){var b=0,c;for(c in a)b++;return b}function Sa(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;for(var d in b)if(!(d in a))return!1;return!0};var Ta=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function Ua(a){return a?decodeURI(a):a};function Va(a){if(a.self===a.top)return!1;if(a.location.origin&&a.location.ancestorOrigins){var b=a.location.origin;return Ja(a.location.ancestorOrigins,function(c){var d=Ua(c.match(Ta)[3]||null)||"";return Aa(".google.com",d.slice(d.length-11))==0||c===b})}return!1}function Wa(a){return a.location.ancestorOrigins&&a.location.ancestorOrigins.length?Na.test(a.location.ancestorOrigins[0]):!1};var Xa=/\[gpay-microapps\/(\d+(\.\d+)*)[^\]]*\]/;function Ya(a,b,c){this.g=a;this.h=b;this.i=c}function Za(a){a=a.split(".");return new Ya(Number(a[0]||""),Number(a[1]||""),Number(a[2]||""))}
function Q(){var a={deviceType:"",j:!1,h:!1,g:0};Ka?a.deviceType="android":La&&(a.deviceType="ios");var b=Xa.exec(Ea().toLocaleLowerCase());b&&b.length>0&&(a.deviceType=="android"&&b[0].includes("dev")?a.j=!0:a.deviceType=="ios"&&b[0].includes("9999.99.99")?a.j=!0:b&&b.length>1&&(a.i=Za(b[1])),b[0].includes("flutter")&&(a.h=!0),b[0].includes("merchant")?a.g=5:a.g=$a(a));return a}
function $a(a){if(!a)return 0;switch(a.deviceType){case "ios":return a.h?2:4;case "android":return a.h?1:3;default:return 0}};function R(){this.g=this.g;this.i=this.i}R.prototype.g=!1;R.prototype.dispose=function(){this.g||(this.g=!0,this.j())};R.prototype[Symbol.dispose]=function(){this.dispose()};R.prototype.j=function(){if(this.i)for(;this.i.length;)this.i.shift()()};function ab(a,b){this.type=a;this.target=b}ab.prototype.g=function(){};var bb=function(){if(!y.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{var c=function(){};y.addEventListener("test",c,b);y.removeEventListener("test",c,b)}catch(d){}return a}();function S(a){ab.call(this,a?a.type:"");this.relatedTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.H=null;if(a){var b=this.type=a.type,c=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;var d=a.relatedTarget;d||(b=="mouseover"?d=a.fromElement:b=="mouseout"&&(d=a.toElement));this.relatedTarget=
d;c?(this.clientX=c.clientX!==void 0?c.clientX:c.pageX,this.clientY=c.clientY!==void 0?c.clientY:c.pageY,this.screenX=c.screenX||0,this.screenY=c.screenY||0):(this.clientX=a.clientX!==void 0?a.clientX:a.pageX,this.clientY=a.clientY!==void 0?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=a.pointerType;
this.state=a.state;this.H=a;a.defaultPrevented&&S.C.g.call(this)}}xa(S,ab);S.prototype.g=function(){S.C.g.call(this);var a=this.H;a.preventDefault?a.preventDefault():a.returnValue=!1};var cb="closure_listenable_"+(Math.random()*1E6|0);var db=0;function eb(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.h=e;this.key=++db;this.g=this.F=!1}function fb(a){a.g=!0;a.listener=null;a.proxy=null;a.src=null;a.h=null};function gb(a){this.src=a;this.g={};this.h=0}gb.prototype.add=function(a,b,c,d,e){var k=a.toString();a=this.g[k];a||(a=this.g[k]=[],this.h++);var f;a:{for(f=0;f<a.length;++f){var g=a[f];if(!g.g&&g.listener==b&&g.capture==!!d&&g.h==e)break a}f=-1}f>-1?(b=a[f],c||(b.F=!1)):(b=new eb(b,this.src,k,!!d,e),b.F=c,a.push(b));return b};var hb="closure_lm_"+(Math.random()*1E6|0),ib={},jb=0;function kb(a,b,c,d,e){if(d&&d.once)return T(a,b,c,d,e);if(Array.isArray(b)){for(var k=0;k<b.length;k++)kb(a,b[k],c,d,e);return null}c=lb(c);return a&&a[cb]?a.g(b,c,A(d)?!!d.capture:!!d,e):mb(a,b,c,!1,d,e)}
function mb(a,b,c,d,e,k){if(!b)throw Error("Invalid event type");var f=A(e)?!!e.capture:!!e,g=nb(a);g||(a[hb]=g=new gb(a));c=g.add(b,c,d,f,k);if(c.proxy)return c;d=ob();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)bb||(e=f),e===void 0&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(pb(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");jb++;return c}
function ob(){function a(c){return b.call(a.src,a.listener,c)}var b=qb;return a}function T(a,b,c,d,e){if(Array.isArray(b)){for(var k=0;k<b.length;k++)T(a,b[k],c,d,e);return null}c=lb(c);return a&&a[cb]?a.h(b,c,A(d)?!!d.capture:!!d,e):mb(a,b,c,!0,d,e)}
function rb(a){if(typeof a!=="number"&&a&&!a.g){var b=a.src;if(b&&b[cb])b.i(a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(pb(c),d):b.addListener&&b.removeListener&&b.removeListener(d);jb--;if(c=nb(b)){d=a.type;if(d in c.g){var e=c.g[d],k=Ia(e,a),f;(f=k>=0)&&Array.prototype.splice.call(e,k,1);f&&(fb(a),c.g[d].length==0&&(delete c.g[d],c.h--))}c.h==0&&(c.src=null,b[hb]=null)}else fb(a)}}}
function pb(a){return a in ib?ib[a]:ib[a]="on"+a}function qb(a,b){if(a.g)a=!0;else{b=new S(b,this);var c=a.listener,d=a.h||a.src;a.F&&rb(a);a=c.call(d,b)}return a}function nb(a){a=a[hb];return a instanceof gb?a:null}var sb="__closure_events_fn_"+(Math.random()*1E9>>>0);function lb(a){if(typeof a==="function")return a;a[sb]||(a[sb]=function(b){return a.handleEvent(b)});return a[sb]};function tb(){var a=this;this.promise=new Promise(function(b,c){a.resolve=b;a.reject=c})};var U=null,ub=new tb;function vb(a){var b,c,d;return w(function(e){if(e.g==1)return U==null&&(U=Q()),null==U||null==U.i?e.return(!0):u(e,ub.promise,2);b=e.i;if(!b.has(a))return e.return(!1);if(U.j)return e.return(!0);c=b.get(a);d=U.i;return e.return(d.g!==c.g?d.g>c.g:d.h!==c.h?d.h>c.h:d.i>=c.i)})};var wb=new Set(["image/jpeg","video/*","application/pdf"]),xb=new Set(["camera","files"]);var V=new Set(["type","enum","const"]);function yb(a,b,c){a=zb(a,b,[c===void 0?"root":c]);return a.length>0?a:null}function W(a,b,c){return"Object:"+a.join(".")+" Validation:"+b+" Constraint:"+c}function Ab(a,b){var c=a.length;if(c>0){for(var d=Array(c),e=0;e<c;e++)d[e]=a[e];a=d}else a=[];a[a.length-1]+="["+b+"]";return a}
function Bb(a,b,c){var d=[];Object.keys(a).forEach(function(e){if(!V.has(e)){var k=!1;switch(e){case "multipleOf":k=typeof b!=="number"||b%a[e]===0;break;case "minimum":k=b>=a[e]||a.exclusiveMinimum&&b>a[e];break;case "maximum":k=b<=a[e]||a.exclusiveMaximum&&b<a[e];break;case "exclusiveMinimum":case "exclusiveMaximum":break;default:throw Error("Unsupported numeric keywords:"+e);}k||d.push(W(c,e,a[e].toString()))}});return d}
function Cb(a,b,c){var d=[];Object.keys(a).forEach(function(e){if(!V.has(e)){switch(e){case "pattern":var k=(new RegExp(a[e])).test(b);break;case "minLength":k=b.length>=a[e];break;case "maxLength":k=b.length<=a[e];break;default:throw Error("Unsupported string keywords:"+e);}k||d.push(W(c,e,a[e].toString()))}});return d}
function Db(a,b,c){var d=[];Object.keys(a).forEach(function(e){if(!V.has(e)){var k=a[e];switch(e){case "items":if(Array.isArray(k))for(e=0;e<k.length;e++){var f=Ab(c,e);f=zb(k[e],b[e],f);f!==null&&(d=O(d,f))}else for(e=0;e<b.length;e++)f=Ab(c,e),f=zb(k,b[e],f),f!==null&&(d=O(d,f));break;case "maxItems":b.length>k&&d.push(W(c,e,k.toString()));break;case "minItems":b.length<k&&d.push(W(c,e,k.toString()));break;case "uniqueItems":if(typeof k!=="boolean")d.push(W(c,e,k.toString()));else if(k){f=new Set;
for(var g=0;g<b.length;g++){var h=JSON.stringify(b[g]);if(f.has(h)){d.push(W(c,e,k.toString()));break}else f.add(h)}}break;default:throw Error("Unsupported array keywords:"+e);}}});return d}
function Eb(a,b,c){var d=[];Object.keys(a).forEach(function(e){if(!V.has(e)){var k=a[e];switch(e){case "required":for(var f=t(k),g=f.next();!g.done;g=f.next())g=g.value,b[g]===void 0&&d.push(W(c,e,g));break;case "properties":Object.keys(b).forEach(function(h){k[h]!==void 0&&(h=zb(k[h],b[h],O(c,h)),h!==null&&(d=O(d,h)))});break;case "minProperties":Ra(b)<k&&d.push(W(c,e,k.toString()));break;case "maxProperties":Ra(b)>k&&d.push(W(c,e,k.toString()));break;case "patternProperties":case "additionalProperties":case "dependencies":case "propertyNames":throw Error("Unsupported object keywords:"+
e);default:throw Error("Unknown object keywords:"+e);}}});return d}
function zb(a,b,c){var d=[];if(a.type!=null){d=a.type;switch(d){case "string":var e=typeof b==="string";break;case "number":e=typeof b==="number";break;case "boolean":e=typeof b==="boolean";break;case "null":e=b===null;break;case "object":e=A(b)&&!Array.isArray(b);break;case "integer":e=typeof b==="number"&&Number.isInteger(b);break;case "array":e=Array.isArray(b);break;case "date":e=A(b)&&typeof b.getFullYear=="function";break;default:throw Error("Unsupported field type: "+d);}d=e?[]:[W(c,"type",
d)]}if(d.length==0&&a["enum"]!=null){d=a["enum"];e=!1;if(A(b))for(var k=t(d),f=k.next();!f.done;f=k.next()){if(Sa(b,f.value)){e=!0;break}}else for(k=t(d),f=k.next();!f.done;f=k.next())if(b===f.value){e=!0;break}d=e?[]:[W(c,"enum",JSON.stringify(d))]}d.length==0&&a["const"]!=null&&(d=a["const"],d=(A(b)?Sa(d,b):b===d)?[]:[W(c,"const",JSON.stringify(d))]);if(d.length)return d;typeof b==="number"?d=Bb(a,b,c):typeof b==="string"?d=Cb(a,b,c):Array.isArray(b)?d=Db(a,b,c):A(b)&&!Array.isArray(b)&&(d=Eb(a,
b,c));return d};var Fb={type:"object",properties:{apiVersion:{type:"number"},apiVersionMinor:{type:"number"},allowedPaymentMethods:{type:"array",items:{type:"object",required:["type"]},minItems:1},transactionInfo:{type:"object",properties:{totalPrice:{type:"string",pattern:"^[0-9]+(\\.[0-9][0-9])?$"},totalPriceStatus:{type:"string"},currencyCode:{type:"string"},transactionNote:{type:"string"}},required:["totalPriceStatus","currencyCode"]}},required:["apiVersion","apiVersionMinor","allowedPaymentMethods","transactionInfo"]},
Gb={type:"object",properties:{type:{type:"string"},parameters:{type:"object",required:["payeeVpa","payeeName","mcc","transactionReferenceId"],properties:{payeeName:{type:"string",minLength:1},transactionReferenceId:{type:"string",minLength:1}}},tokenizationSpecification:{type:"object",properties:{type:{type:"string","enum":["DIRECT"]}},required:["type"]}},required:["parameters","tokenizationSpecification","type"]},Hb={type:"object",properties:{text:{type:"string",maxLength:150},url:{type:"string",
maxLength:2E3,pattern:"^https://microapps.google.com/"},title:{type:"string",maxLength:80},imageUrl:{type:"string",maxLength:2E3},microappId:{type:"string",maxLength:25},shareSections:{type:"array",items:{type:"string"}}}},Ib={type:"object",properties:{allowedMimeTypes:{type:"array",items:{type:"string"},minItems:1},allowedSources:{type:"array",items:{type:"string"}},cameraDirection:{type:"string","enum":["front","back"]},maxVideoSeconds:{type:"number",minimum:1,maximum:5}},required:["allowedMimeTypes"]};function Jb(a){var b=yb(Fb,a,"paymentRequest");if(b)return X(JSON.stringify(b));b=t(a.allowedPaymentMethods);for(var c=b.next();!c.done;c=b.next()){c=c.value;var d;a:{if(c.type==="UPI"&&(d=yb(Gb,c))){d=JSON.stringify(d);break a}d=null}if(d)return X(d);if(c=Kb(c,a.transactionInfo))return X(c)}return a.environment&&(a=Lb(a.allowedPaymentMethods,a.environment))?X(a):null}
function Mb(a){if(a==null||!A(a))return X("Valid mediaRequest object is required for this API.");var b=yb(Ib,a,"mediaRequest");if(b)return X(JSON.stringify(b));b=t(a.allowedMimeTypes);for(var c=b.next();!c.done;c=b.next())if(c=wb.has(c.value)?null:"Request must contain supported media types.")return X(c);if(b=a.allowedMimeTypes.length==1&&a.allowedMimeTypes[0]==="video/*")b=Q(),b=!(b.j||(b.g==1||b.g==3)&&b.i.g>54||Nb(b)||b.g===2&&b.i.g>115);if(b)return X("Client does not support video requests. Please update the Google Pay app.");
b=Q();b=b.j||(b.g==1||b.g==3)&&b.i.g>57||Nb(b)||b.g===2&&b.i.g>115;if(a.allowedMimeTypes.length===1&&a.allowedMimeTypes[0]==="application/pdf"&&!b)return X("Client does not support file requests. Please update the Google Pay app.");if(!a.allowedSources)return null;c=t(a.allowedSources);for(var d=c.next();!d.done;d=c.next())if(d=xb.has(d.value)?null:"Request must contain supported media sources.")return X(d);return a.allowedSources.length!==1||a.allowedSources[0]!=="files"||b?a.allowedSources.length===
1&&a.allowedSources[0]==="camera"&&a.allowedMimeTypes.includes("application/pdf")?X('Not possible to request "application/pdf" MIME type with only "camera" in "allowedSources"'):null:X("CLIENT_UNSUPPORTED_FOR_FILES")}
function Kb(a,b){if(b.totalPriceStatus!=="NOT_CURRENTLY_KNOWN"&&!(Number(b.totalPrice)>0))return"Amount must be greater than 0";if(a.type==="UPI"){if(b.totalPriceStatus!=="FINAL")return'Only "FINAL" is supported now in totalPriceStatus for UPI payment type.';if(b.currencyCode!=="INR")return'Only "INR" is currently supported in currencyCode for UPI payment type.'}else if(a.type==="CARD"&&!b.transactionId)return"transactionInfo.transactionId is required.";return null}
function Lb(a,b){return a.find(function(c){return c.type==="CARD"})?b!="TEST"?'only "TEST" environment is supported for CARD payment type.':null:'"environment" is supported for CARD payment type only.'}function Nb(a){var b=a.i;return a.g==5&&(b.g>1||b.g==1&&b.h>=23)}function X(a){return new D(a,3)};function Ob(a){var b=this;this.g=a;this.j=0;this.h=new Map;this.l=new Promise(function(c){return b.u=c});this.g.addEventListener("message",this.i.bind(this));this.g.start()}Ob.prototype.i=function(a){if((a=a.data)&&a.id!=null)if(a.type===0)a.name==="acceptConnection"&&this.u();else if(a.type===1){var b=a.id,c=this.h.get(b);c&&(this.h.delete(b),a.error!=null?c.reject(new D("Request "+a.name+" failed: "+a.error,a.errorCode)):c.resolve(a.data))}};
Ob.prototype.m=function(a,b,c){var d=this;c=c===void 0?!0:c;var e=++this.j,k=Promise.resolve();c&&(k=new Promise(function(g,h){d.h.set(e,{resolve:g,reject:h})}));var f={id:e,type:0,name:a,data:b,isResponseRequired:c};this.l.then(function(){d.g.postMessage(f)});return k};function Y(a){R.call(this);this.l=a;this.h={}}xa(Y,R);var Pb=[];function Qb(a,b,c){var d="nativeBridge";Array.isArray(d)||(d&&(Pb[0]=d.toString()),d=Pb);for(var e=0;e<d.length;e++){var k=kb(b,d[e],c||a.handleEvent,!1,a.l||a);if(!k)break;a.h[k.key]=k}}function Rb(a){Qa(a.h,function(b,c){this.h.hasOwnProperty(c)&&rb(b)},a);a.h={}}Y.prototype.j=function(){Y.C.j.call(this);Rb(this)};Y.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Sb(a){this.h=a;this.i=new Y(this);Tb(this);this.g=null}function Ub(a,b){Ka?(a=a.h.paisaJSHost_,a!=null&&a.callNative(JSON.stringify(b))):La&&(a=a.h.webkit.messageHandlers.paisaJSHost_,a!=null&&a.postMessage(JSON.stringify(b)))}function Vb(a,b){a.g=b}function Tb(a){Qb(a.i,a.h,function(b){b=b.H;b.detail!=null&&a.g!=null&&a.g(b.detail)})};var Wb=Ma(function(a){return typeof a==="number"}),Xb=Ma(function(a){return typeof a==="string"}),Yb=Ma(function(a){return!!a&&(typeof a==="object"||typeof a==="function")});function Zb(a){var b=this;this.j=Math.floor(Math.random()*65535);this.i=this.h=null;this.g=new Map;this.host=new Sb(a);Vb(this.host,function(c){if(Yb(c)&&Xb(c.status)&&(c.status==="success"||c.status==="failure")&&Wb(c.id)){var d=c.data;if(c.id===b.i)b.h!=null&&Xb(d)&&b.h.resolve(d);else{var e=b.g.get(c.id);e&&(b.g.delete(c.id),c.method!==e.request.method?e.S.reject(new D("Method names in request and response are not the same. Request:"+(e.request.method+" Response:"+c.method))):c.status==="success"?
e.S.resolve(d):e.S.reject(new D(d,c.errorCode)))}}});this.h=new tb;this.i=$b(this);Ub(this.host,{token:"",method:"startConnection",id:this.i,data:{},isResponseRequired:!0});this.l=this.h.promise}Zb.prototype.m=function(a,b,c){c=c===void 0?!0:c;var d=this,e,k,f,g;return w(function(h){if(h.g==1)return u(h,d.l,2);e=h.i;k=$b(d);f={token:e,method:a,id:k,data:b,isResponseRequired:c};Ub(d.host,f);if(!c)return h.return(Promise.resolve());g=new tb;d.g.set(k,{S:g,request:f});return h.return(g.promise)})};
function $b(a){var b=a.j;a.j=(b+1)%65535;a.g.has(b);return b};var ac=null;
function bc(){var a=window;if(a.self===a.top&&Q().h)this.g=new Zb(a);else{var b=ac=new MessageChannel;try{var c=a.self!==a.top}catch(e){c=!0}if(!c)throw Error("Unsupported environment: expected running in iframe");c=new Ob(b.port1);if(!a.location.ancestorOrigins||!a.location.ancestorOrigins.length)throw Error("unsupported environment");var d=a.location.ancestorOrigins[0];if(!Na.test(d))throw Error("unknown viewer origin");a.parent.postMessage({type:0,name:"requestConnection"},d,[b.port2]);this.g=
c}}bc.prototype.m=function(a,b,c){return this.g.m(a,b,c===void 0?!0:c)};var cc=da(["about:blank"]),dc=null;function ec(){var a=window;this.g=new bc;this.h=a}function fc(){dc||(dc=new ec);return dc}n=ec.prototype;n.D=function(){var a;(a=this.h.self===this.h.top)||(a=this.h,a=Va(a)&&Wa(a));if(a)gc(this,"sdkload");else{a=this.h.location;var b=Oa(cc);if(b instanceof P)if(b instanceof P)b=b.g;else throw Error("");else b=Pa.test(b)?b:void 0;b!==void 0&&(a.href=b)}};function gc(a,b,c){a.g.m("appLoadingComplete",{loadType:b,loadTimeMs:c===void 0?null:c})}
n.K=function(a){var b=this,c,d,e,k;return w(function(f){if(f.g==1)return c=a||{},d="getIdentity",u(f,b.v("nativeGetIdentity"),2);if(f.g!=3)return e=f.i,u(f,b.v("webGetIdentity"),3);(k=f.i)?d="getIdentity":e&&(d="nativeGetIdentity");return f.return(b.g.m(d,c))})};n.P=function(a){var b=Jb(a);return b?Promise.reject(b):this.g.m("requestPayment",a)};
n.R=function(a){var b;if(b=(b=yb(Hb,a,"sharingRequest"))?X(JSON.stringify(b)):null)return Promise.reject(b);hc(a.imageUrl)||(a.imageUrl="");return this.g.m("requestSharing",a)};n.G=function(a){var b=this,c,d;return w(function(e){if(e.g==1)return(c=a!=null&&A(a)?null:X("Valid order object is required for this API."))?e.return(Promise.reject(c)):u(e,b.g.m("createOrder",a),2);d=e.i;typeof d==="object"&&(d.toString=function(){return JSON.stringify(d)});return e.return(d)})};
n.J=function(a){return this.g.m("getCurrentLocation",a||{})};n.L=function(a){return this.g.m("getPhoneNumber",a||{})};n.N=function(a){this.g.m("openUrl",a).catch(function(){})};n.M=function(a){return this.g.m("openGpayPage",a||{})};n.O=function(a){var b=Mb(a);return b?Promise.reject(b):this.g.m("requestMedia",a)};n.I=function(a){return this.g.m("getAddress",a||{})};n.v=function(a){return vb(a)};n.enableScreenshotPrevention=function(a){this.g.m("enableScreenshotPrevention",a).catch(function(){})};
function hc(a){if(!a||(a.match(Ta)[1]||"").toLowerCase()!=="https")return!1;var b=Ua(a.match(Ta)[3]||null)||"";return[".google.com",".googleapis.com",".gstatic.com",".googleusercontent.com"].some(function(c){return Aa(c,b.slice(b.length-c.length))==0})}
(function(a){var b,c;return w(function(d){b=window;if(!(Va(b)&&Wa(b)||b.self===b.top&&Q().h))return d.return();c=new Map;a().then(function(e){e=e.allowedFeatureConfigs;Array.isArray(e)&&(e.forEach(function(k){return c.set(k.feature,Za(k.minVersion||""))}),ub.resolve(c))});d.g=0})})(function(){return fc().g.m("getAllowedFeatureConfigs",{})});
(function(a){var b=window;if(b.self===b.top&&Q().h)if(b.PerformanceObserver&&(b.PerformanceObserver.supportedEntryTypes||[]).includes("navigation"))try{(new b.PerformanceObserver(function(c){c=t(c.getEntries());for(var d=c.next();!d.done;d=c.next())d=d.value,d.type==="navigate"&&d.duration>0&&a(d.duration)})).observe({type:"navigation",buffered:!0})}catch(c){T(b,"load",function(){return a(null)})}else T(b,"load",function(){return a(null)})})(function(a){return gc(fc(),"onload",a)});
(function(a){try{var b=window;(Va(b)&&Wa(b)||b.self===b.top&&Q().h)&&T(b,"load",function(){if(b.performance&&b.performance.getEntriesByType&&b.performance.getEntriesByType("paint").length!=0){var c=b.performance.getEntriesByType("paint");c=t(c);for(var d=c.next();!d.done;d=c.next())switch(d=d.value,d.name){case "first-contentful-paint":a(d.startTime+d.duration)}}})}catch(c){}})(function(a){return void gc(fc(),"fcp",a)});var Z;H=function(){return fc()};Z=new za;C("microapps.getIdentity",Z.K);C("microapps.requestPayment",Z.P);C("microapps.createOrder",Z.G);C("microapps.initialize",Z.D);C("microapps.getCurrentLocation",Z.J);C("microapps.getPhoneNumber",Z.L);C("microapps.openUrl",Z.N);C("microapps.openGpayPage",Z.M);C("microapps.requestSharing",Z.R);C("microapps.requestMedia",Z.O);C("microapps.getAddress",Z.I);C("microapps.checkFeatureAvailability",Z.v);
C("microapps.environment",function(){return Xa.test(Ea().toLocaleLowerCase())?"gpay-microapps":""});}).call(this);
